In [8]:
import pickle
import numpy as np

In [9]:
ohe_sex = pickle.load(open("ohe_sex.pkl","rb"))
clf = pickle.load(open("clf.pkl","rb"))

In [69]:
test_input = np.array([522,2,"male",31.0,0,0,10.5,3],dtype = object).reshape(1,8)

In [70]:
test_input

array([[522, 2, 'male', 31.0, 0, 0, 10.5, 3]], dtype=object)

In [71]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\Mayank\Downloads\python.Mayank\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0.]])

In [72]:
test_input_transformed = np.concatenate((test_input[:,[0,1,3,4,5,6,7]],test_input_sex),axis = 1 )

In [73]:
test_input_transformed.shape

(1, 9)

In [74]:
clf.predict(test_input_transformed)

array([1])